/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kkrfqweqapnhcnjlzmvm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrcmZxd2VxYXBuaGNuamx6bXZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyNzg1NzEsImV4cCI6MjA5MTg1NDU3MX0.pz2EkX-xNE2NFtCaUMNKR6BinqJnZLM61K1QUs-g4ZM"